version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - app-network
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/mem:/dev/mem
    privileged: true
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge